<?php

namespace Modules\Countries\Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Database\Eloquent\Model;

class CountriesDatabaseSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        \DB::table('countries')->insert(
            [
                array('iso2'=>'AF','country'=>'Afghanistan'),
                array('iso2'=>'AL','country'=>'Albania'),
                array('iso2'=>'DZ','country'=>'Algeria'),
                array('iso2'=>'AS','country'=>'American Samoa'),
                array('iso2'=>'AD','country'=>'Andorra'),
                array('iso2'=>'AO','country'=>'Angola'),
                array('iso2'=>'AI','country'=>'Anguilla'),
                array('iso2'=>'AQ','country'=>'Antarctica'),
                array('iso2'=>'AG','country'=>'Antigua and Barbuda'),
                array('iso2'=>'AR','country'=>'Argentina'),
                array('iso2'=>'AM','country'=>'Armenia'),
                array('iso2'=>'AW','country'=>'Aruba'),
                array('iso2'=>'AU','country'=>'Australia'),
                array('iso2'=>'AT','country'=>'Austria'),
                array('iso2'=>'AZ','country' =>'Azerbaijan'),
                array('iso2'=>'BS','country' =>'Bahamas'),
                array('iso2'=>'BH','country' =>'Bahrain'),
                array('iso2'=>'BD','country' => 'Bangladesh'),
                array('iso2'=>'BB','country' => 'Barbados'),
                array('iso2'=>'BY','country' => 'Belarus'),
                array('iso2'=>'BE','country' => 'Belgium'),
                array('iso2'=>'BZ','country' => 'Belize'),
                array('iso2'=>'BJ','country' => 'Benin'),
                array('iso2'=>'BM','country' => 'Bermuda'),
                array('iso2'=>'BT','country' => 'Bhutan'),
                array('iso2'=>'BO','country' => 'Bolivia'),
                array('iso2'=>'BA','country' => 'Bosnia and Herzegovina'),
                array('iso2'=>'BW','country' => 'Botswana'),
                array('iso2'=>'BV','country' => 'Bouvet Island'),
                array('iso2'=>'BR','country' => 'Brazil'),
                array('iso2'=>'BQ','country' => 'British Antarctic Territory'),
                array('iso2'=>'IO','country' => 'British Indian Ocean Territory'),
                array('iso2'=>'VG','country' => 'British Virgin Islands'),
                array('iso2'=>'BN','country' => 'Brunei'),
                array('iso2'=>'BG','country' => 'Bulgaria'),
                array('iso2'=>'BF','country' => 'Burkina Faso'),
                array('iso2'=>'BI','country' => 'Burundi'),
                array('iso2'=>'KH','country' => 'Cambodia'),
                array('iso2'=>'CM','country' => 'Cameroon'),
                array('iso2'=>'CA','country' => 'Canada'),
                array('iso2'=>'CT','country' => 'Canton and Enderbury Islands'),
                array('iso2'=>'CV','country' => 'Cape Verde'),
                array('iso2'=>'KY','country' => 'Cayman Islands'),
                array('iso2'=>'DM','country' => 'Dominica'),
                array('iso2'=>'DO','country' => 'Dominican Republic'),
                array('iso2'=>'NQ','country' => 'Dronning Maud Land'),
                array('iso2'=>'DD','country' => 'East Germany'),
                array('iso2'=>'EC','country' => 'Ecuador'),
                array('iso2'=>'EG','country' => 'Egypt'),
                array('iso2'=>'SV','country' => 'El Salvador'),
                array('iso2'=>'GQ','country' => 'Equatorial Guinea'),
                array('iso2'=>'ER','country' => 'Eritrea'),
                array('iso2'=>'EE','country' => 'Estonia'),
                array('iso2'=>'ET','country' => 'Ethiopia'),
                array('iso2'=>'FK','country' => 'Falkland Islands'),
                array('iso2'=>'FO','country' => 'Faroe Islands'),
                array('iso2'=>'FJ','country' => 'Fiji'),
                array('iso2'=>'FI','country' => 'Finland'),
                array('iso2'=>'FR','country' => 'France'),
                array('iso2'=>'GF','country' => 'French Guiana'),
                array('iso2'=>'PF','country' => 'French Polynesia'),
                array('iso2'=>'TF','country' => 'French Southern Territories'),
                array('iso2'=>'FQ','country' => 'French Southern and Antarctic Territories'),
                array('iso2'=>'GA','country' => 'Gabon'),
                array('iso2'=>'GM','country' => 'Gambia'),
                array('iso2'=>'GE','country' => 'Georgia'),
                array('iso2'=>'DE','country' => 'Germany'),
                array('iso2'=>'GH','country' => 'Ghana'),
                array('iso2'=>'GI','country' => 'Gibraltar'),
                array('iso2'=>'GR','country' => 'Greece'),
                array('iso2'=>'GL','country' => 'Greenland'),
                array('iso2'=>'GD','country' => 'Grenada'),
                array('iso2'=>'GP','country' => 'Guadeloupe'),
                array('iso2'=>'GU','country' => 'Guam'),
                array('iso2'=>'GT','country' => 'Guatemala'),
                array('iso2'=>'GG','country' => 'Guernsey'),
                array('iso2'=>'GN','country' => 'Guinea'),
                array('iso2'=>'GW','country' => 'Guinea-Bissau'),
                array('iso2'=>'GY','country' => 'Guyana'),
                array('iso2'=>'HT','country' => 'Haiti'),
                array('iso2'=>'HM','country' => 'Heard Island and McDonald Islands'),
                array('iso2'=>'HN','country' => 'Honduras'),
                array('iso2'=>'HK','country' => 'Hong Kong SAR China'),
                array('iso2'=>'HU','country' => 'Hungary'),
                array('iso2'=>'IS','country' => 'Iceland'),
                array('iso2'=>'JT','country' => 'Johnston Island'),
                array('iso2'=>'JO','country' => 'Jordan'),
                array('iso2'=>'KZ','country' => 'Kazakhstan'),
                array('iso2'=>'KE','country' => 'Kenya'),
                array('iso2'=>'KI','country' => 'Kiribati'),
                array('iso2'=>'KW','country' => 'Kuwait'),
                array('iso2'=>'KG','country' => 'Kyrgyzstan'),
                array('iso2'=>'LA','country' => 'Laos'),
                array('iso2'=>'LV','country' => 'Latvia'),
                array('iso2'=>'LB','country' => 'Lebanon'),
                array('iso2'=>'LS','country' => 'Lesotho'),
                array('iso2'=>'LR','country' => 'Liberia'),
                array('iso2'=>'LY','country' => 'Libya'),
                array('iso2'=>'LI','country' => 'Liechtenstein'),
                array('iso2'=>'LT','country' => 'Lithuania'),
                array('iso2'=>'LU','country' => 'Luxembourg'),
                array('iso2'=>'MO','country' => 'Macau SAR China'),
                array('iso2'=>'MK','country' => 'Macedonia'),
                array('iso2'=>'MG','country' => 'Madagascar'),
                array('iso2'=>'MW','country' => 'Malawi'),
                array('iso2'=>'MY','country' => 'Malaysia'),
                array('iso2'=>'MV','country' => 'Maldives'),
                array('iso2'=>'ML','country' => 'Mali'),
                array('iso2'=>'MT','country' => 'Malta'),
                array('iso2'=>'MH','country' => 'Marshall Islands'),
                array('iso2'=>'MQ','country' => 'Martinique'),
                array('iso2'=>'MR','country' => 'Mauritania'),
                array('iso2'=>'MU','country' => 'Mauritius'),
                array('iso2'=>'YT','country' => 'Mayotte'),
                array('iso2'=>'FX','country' => 'Metropolitan France'),
                array('iso2'=>'MX','country' => 'Mexico'),
                array('iso2'=>'FM','country' => 'Micronesia'),
                array('iso2'=>'MI','country' => 'Miso2way Islands'),
                array('iso2'=>'MD','country' => 'Moldova'),
                array('iso2'=>'MC','country' => 'Monaco'),
                array('iso2'=>'MN','country' => 'Mongolia'),
                array('iso2'=>'ME','country' => 'Montenegro'),
                array('iso2'=>'MS','country' => 'Montserrat'),
                array('iso2'=>'MA','country' => 'Morocco'),
                array('iso2'=>'MZ','country' => 'Mozambique'),
                array('iso2'=>'MM','country' => 'Myanmar [Burma]'),
                array('iso2'=>'NA','country' => 'Namibia'),
                array('iso2'=>'NR','country' => 'Nauru'),
                array('iso2'=>'NP','country' => 'Nepal'),
                array('iso2'=>'NL','country' => 'Netherlands'),
                array('iso2'=>'AN','country' => 'Netherlands Antilles'),
                array('iso2'=>'NT','country' => 'Neutral Zone'),
                array('iso2'=>'NC','country' => 'New Caledonia'),
                array('iso2'=>'NZ','country' => 'New Zealand'),
                array('iso2'=>'NI','country' => 'Nicaragua'),
                array('iso2'=>'NE','country' => 'Niger'),
                array('iso2'=>'NG','country' => 'Nigeria'),
                array('iso2'=>'NU','country' => 'Niue'),
                array('iso2'=>'NF','country' => 'Norfolk Island'),
                array('iso2'=>'KP','country' => 'North Korea'),
                array('iso2'=>'VD','country' => 'North Vietnam'),
                array('iso2'=>'MP','country' => 'Northern Mariana Islands'),
                array('iso2'=>'NO','country' => 'Norway'),
                array('iso2'=>'OM','country' => 'Oman'),
                array('iso2'=>'PC','country' => 'Pacific Islands Trust Territory'),
                array('iso2'=>'PK','country' => 'Pakistan'),
                array('iso2'=>'PW','country' => 'Palau'),
                array('iso2'=>'PS','country' => 'Palestinian Territories'),
                array('iso2'=>'PA','country' => 'Panama'),
                array('iso2'=>'PZ','country' => 'Panama Canal Zone'),
                array('iso2'=>'PG','country' => 'Papua New Guinea'),
                array('iso2'=>'PY','country' => 'Paraguay'),
                array('iso2'=>'YD','country' => 'People\'s Democratic Republic of Yemen'),
                array('iso2'=>'PE','country' => 'Peru'),
                array('iso2'=>'PH','country' => 'Philippines'),
                array('iso2'=>'PN','country' => 'Pitcairn Islands'),
                array('iso2'=>'PL','country' => 'Poland'),
                array('iso2'=>'PT','country' => 'Portugal'),
                array('iso2'=>'PR','country' => 'Puerto Rico'),
                array('iso2'=>'QA','country' => 'Qatar'),
                array('iso2'=>'RO','country' => 'Romania'),
                array('iso2'=>'RU','country' => 'Russia'),
                array('iso2'=>'RW','country' => 'Rwanda'),
                array('iso2'=>'RE','country' => 'Réunion'),
                array('iso2'=>'BL','country' => 'Saint Barthélemy'),
                array('iso2'=>'SH','country' => 'Saint Helena'),
                array('iso2'=>'KN','country' => 'Saint Kitts and Nevis'),
                array('iso2'=>'LC','country' => 'Saint Lucia'),
                array('iso2'=>'MF','country' => 'Saint Martin'),
                array('iso2'=>'PM','country' => 'Saint Pierre and Miquelon'),
                array('iso2'=>'VC','country' => 'Saint Vincent and the Grenadines'),
                array('iso2'=>'WS','country' => 'Samoa'),
                array('iso2'=>'SM','country' => 'San Marino'),
                array('iso2'=>'SA','country' => 'Saudi Arabia'),
                array('iso2'=>'SN','country' => 'Senegal'),
                array('iso2'=>'RS','country' => 'Serbia'),
                array('iso2'=>'CS','country' => 'Serbia and Montenegro'),
                array('iso2'=>'SC','country' => 'Seychelles'),
                array('iso2'=>'SL','country' => 'Sierra Leone'),
                array('iso2'=>'SG','country' => 'Singapore'),
                array('iso2'=>'SK','country' => 'Slovakia'),
                array('iso2'=>'SI','country' => 'Slovenia'),
                array('iso2'=>'SB','country' => 'Solomon Islands'),
                array('iso2'=>'SO','country' => 'Somalia'),
                array('iso2'=>'ZA','country' => 'South Africa'),
                array('iso2'=>'GS','country' => 'South Georgia and the South Sandwich Islands'),
                array('iso2'=>'KR','country' => 'South Korea'),
                array('iso2'=>'ES','country' => 'Spain'),
                array('iso2'=>'LK','country' => 'Sri Lanka'),
                array('iso2'=>'SD','country' => 'Sudan'),
                array('iso2'=>'SR','country' => 'Suricountry'),
                array('iso2'=>'SJ','country' => 'Svalbard and Jan Mayen'),
                array('iso2'=>'SZ','country' => 'Swaziland'),
                array('iso2'=>'SE','country' => 'Sweden'),
                array('iso2'=>'CH','country' => 'Switzerland'),
                array('iso2'=>'SY','country' => 'Syria'),
                array('iso2'=>'ST','country' => 'São Tomé and Príncipe'),
                array('iso2'=>'TW','country' => 'Taiwan'),
                array('iso2'=>'TJ','country' => 'Tajikistan'),
                array('iso2'=>'TZ','country' => 'Tanzania'),
                array('iso2'=>'TH','country' => 'Thailand'),
                array('iso2'=>'TL','country' => 'Timor-Leste'),
                array('iso2'=>'TG','country' => 'Togo'),
                array('iso2'=>'TK','country' => 'Tokelau'),
                array('iso2'=>'TO','country' => 'Tonga'),
                array('iso2'=>'TT','country' => 'Triniso2ad and Tobago'),
                array('iso2'=>'TN','country' => 'Tunisia'),
                array('iso2'=>'TR','country' => 'Turkey'),
                array('iso2'=>'TM','country' => 'Turkmenistan'),
                array('iso2'=>'TC','country' => 'Turks and Caicos Islands'),
                array('iso2'=>'TV','country' => 'Tuvalu'),
                array('iso2'=>'UM','country' => 'U.S. Minor Outlying Islands'),
                array('iso2'=>'PU','country' => 'U.S. Miscellaneous Pacific Islands'),
                array('iso2'=>'VI','country' => 'U.S. Virgin Islands'),
                array('iso2'=>'UG','country' => 'Uganda'),
                array('iso2'=>'UA','country' => 'Ukraine'),
                array('iso2'=>'SU','country' => 'Union of Soviet Socialist Republics'),
                array('iso2'=>'AE','country' => 'United Arab Emirates'),
                array('iso2'=>'GB','country' => 'United Kingdom'),
                array('iso2'=>'US','country' => 'United States'),
                array('iso2'=>'ZZ','country' => 'Unknown or Invaliso2 Region'),
                array('iso2'=>'UY','country' => 'Uruguay'),
                array('iso2'=>'UZ','country' => 'Uzbekistan'),
                array('iso2'=>'VU','country' => 'Vanuatu'),
                array('iso2'=>'VA','country' => 'Vatican City'),
                array('iso2'=>'VE','country' => 'Venezuela'),
                array('iso2'=>'VN','country' => 'Vietnam'),
                array('iso2'=>'WK','country' => 'Wake Island'),
                array('iso2'=>'WF','country' => 'Wallis and Futuna'),
                array('iso2'=>'EH','country' => 'Western Sahara'),
                array('iso2'=>'YE','country' => 'Yemen'),
                array('iso2'=>'ZM','country' => 'Zambia'),
                array('iso2'=>'ZW','country' => 'Zimbabwe'),
                array('iso2'=>'AX','country' => 'Åland Islands')
            ]
        );
    }
}
